version: '3.8'

services:

  backend:
    build: 
      context: ./backend/
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "127.0.0.1:8000:8000"
    expose:
      - 8000
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  frontend:
    build: 
      context: ./frontend/
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - backend
    tty: true
    volumes:
      - /app/data
    command: npm start

